jobs:
    css: "li.jobposts-item"
    multiple: true
    children:
        title:
            css: "h3"
            type: Text

        url:
            css: "a.jobpost-mainlink"
            type: Link

        company:
            css: ".custom-profile-label--secondary"
            type: Text